CU.OnBoarding.Web/Controllers/EmailLogController.cs
using CU.OnBoarding.DataAccess;
using CU.OnBoarding.DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CU.OnBoarding.Web.Controllers
{
    public class EmailLogController : BaseController
    {
        // GET: EmailLog
        public ActionResult Index()
        {
            EmailLogViewModel model = new EmailLogViewModel();
            EmailTemplateService es = new EmailTemplateService();
            model.lstResults = es.EmailLogs.ToList();
            return View(model);
        }

        public ActionResult DownLoadAttchment(int Id)
        {
            EmailTemplateService es = new EmailTemplateService();
            var data = es.GetEmailFileContent(Id);
            if (data != null)
            {
                return File(data.FileData.ToArray(), "application/text", data.AttchmentFileName);
            }
            return Content("No data found for file");
        }
    }
}

CU.OnBoarding.Web/Views/EmailLog/Index.cshtml
@model CU.OnBoarding.DataAccess.Model.EmailLogViewModel
@{
    ViewBag.Title = "Email Logs";
    ViewBag.Page = "emaillog";
}


<header class="page-header">
    <h2>Email Logs</h2>

</header>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title"></h2>
            </header>
            <div class="panel-body">
                @using (Html.BeginForm("Index", "EmailLog", FormMethod.Post, new { @class = "form-horizontal form-bordered", onsubmit = "showLoader(this);" }))
                {
                    <div class="panel-body">
                        @*<div class="form-group">
                            <div class="col-md-12">
                                <a href="~/EmailTemplate/Add/0" class="mb-xs mt-xs mr-xs btn btn-success"><i class="fas fa-user-plus"></i>  Add New Template</a>
                            </div>
                            d
                        </div>*@
                        <table class="table table-bordered table-striped mb-none" id="datatable-default">
                            <thead>
                                <tr>
                                    <th>To Email</th>
                                    <th>Subject</th>
                                    <th>Attchment Name</th>
                                    <th>Email Sent Date</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.lstResults.Count > 0)
                                {
                                    foreach (var item in Model.lstResults)
                                    {
                                        <tr>
                                            <td>@item.ToEmail</td>
                                            <td>@item.Subject</td>
                                            <td> <a href="~/EmailLog/DownLoadAttchment/@item.Id">@item.AttchmentFileName</a></td>
                                            <td>@item.EmailSentDt.ToString("MM/dd/yyyy")</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>


                    </div>
                    @*<footer class="panel-footer"></footer>*@
                }
            </div>
        </section>


    </div>
</div>
@section scripts{

    <script type="text/javascript">

        $(document).ready(function () {
            $('#datatable-default').dataTable();
        });
    </script>
}